### PR TITLE
Allow any instance of application became secondary

### PR DESCRIPTION
**Pull request by wadealer**
Add allowSecondary static property to SingleApplication class. 
Sometimes using '--secondary' command line key is not possible. Added static property allows any instance of program starts as secondary.

### CODE REVIEW

**Comment by itay-grudev** [comment]
Your proposal is quite reasonable, but I think your solution could be improved.

**Comment by itay-grudev** [comment]
I can't accept that. This library is supposed to be very lightweight and I won't use JSON for data transfer. An exposed `QDataStream` is a much more appropriate option in my opinion.

**Comment by wadealer** [comment]
Hm, sorry. I don't want the last commit be in this pull request. It's only for my purposes.

**Comment by itay-grudev** [comment]
The idea for secondary instances to communicate is a good one. I will add such an API to the next version.

**Comment by itay-grudev** [comment]
I'll add support for allowing a secondary instance with a boolean flag directly in the constructor (the third argument). This would replace the current maximum number of secondary instances. I'll also expose the local socket so secondary instances will be able to communicate with the primary one. I will also expose two methods that will allow you to see how many active instances in total are there and which one are you (1-st [primary], 2-nd, 3-rd, etc).

I'll try to do that by the end of the week. I hope that will help your project.

**Comment by itay-grudev** [comment]
Since the new version of SingleApplication supports this I will close this pull request.

**Pull request closed without merging**
