### PR TITLE
[Windows] Bind GetUserName at runtime

### PR DESCRIPTION
**Pull request by char101**
I have tested that it compiles and run.

### CODE REVIEW

**Comment by itay-grudev** [comment]
Thank you! I'll review it and merge it later today. Could you give me your full name so I can give you credit it my `CHANGELOG.md`.

**Comment by char101** [comment]
My full name is Charles Gunawan.

**Comment by char101** [comment]
Sorry, I blindly forgot about the Windows headers and `LoadLibrary`, both which requires Windows Platform SDK. Considering that installing Visual Studio nowadays automatically installs the Platform SDK anyway, I vote to stick with your previous implementation since it is simpler.

**Comment by itay-grudev** [comment]
Nevertheless, thank a lot for your efforts. I'll mention you on my next CHANGELOG entry.

**Pull request closed without merging**
