### PR TITLE
WIP Add cmake files

### PR DESCRIPTION
**Pull request by jonaski**
I use SingleApplication for my project now: https://github.com/jonaski/strawberry
It is packed by several linux distros including opensuse and fedora.
To get SingleApplication packed as a library we need some sort of build system that can make it build as the desired class without duplicating the code.
Here is an suggestion using cmake
You can then build using cmake .. -DQAPPLICATION_CLASS=QApplication
or: cmake .. -DQAPPLICATION_CLASS=QCoreApplication
The cmake will then create the header file based on what class is used, singleapplicaiton.h will be created for QApplication and singlecoreapplication.h for QCoreApplication.

### CODE REVIEW

**Comment by itay-grudev** [comment]
I was reluctant to merging it, but I was planning to keep this PR around in case someone finds is useful. Why did you close it?

**Comment by jonaski** [comment]
I opened a new PR, as I use the PR as patch to package singleapplication as a library on opensuse:
https://github.com/itay-grudev/SingleApplication/pull/64.patch

If you don't want to use cmake, could you create a similar approach using qmake, with a .pc file so we can package it as a library? I don't have experience with qmake.

**Comment by itay-grudev** [comment]
I'm not sure about the advantages of distributing it as a library. It will have to be statically linked for performance and to avoid comparability problems.

What exactly was the problem you were having?

**Comment by jonaski** [comment]
You know about the advantages, but you are not sure about them? Why are you not sure about the advantages of distributing it as a library?
I didn't know there would performance issues, and I don't really understand why since it's a small library. I've noticed no performance issues. And I thought the versioning of the shared objects would prevent any comparability problems.
What problem are you referring to?
Anyway, I think it's pointless leaving a PR for this open, when you have already decided that you don't want it distributed as library.

**Pull request closed without merging**
