### PR TITLE
Bug Fix: Typo in Doxygen deploy workflow step

### PR DESCRIPTION
**Pull request by itay-grudev**

### CODE REVIEW

**Comment by itay-grudev** [comment]
@Shatur Can you quickly approve this?

**Review by Shatur — CHANGES_REQUESTED** [review]
Looks good, but we probably need to remove the mention of the `main` branch (since we only have master).

**Comment by Shatur** [comment]
And I think we should add a CMake option to disable doxygen generation. Otherwise it will always be generated if doxygen found on system.

**Comment by itay-grudev** [comment]
@Shatur Removed `main`. We can add an option for building the documentation explicitly at some point in the future. I'm not super worried as it's super-fast and doesn't really use any space.

**Comment by itay-grudev** [comment]
@Shatur That's a good point. Let's make a separate MR for that and get it resolved asap. Will you write it or should I?

**Comment by itay-grudev** [comment]
I'm also working. I have two more important meetings today and a really busy day tomorrow, so I can look into it on Friday the earliest.

**Comment by Shatur** [comment]
> I'm also working. I have two more important meetings today and a really busy day tomorrow, so I can look into it on Friday the earliest.

No problem, I will send a PR today then.

> @Shatur It works: https://itay-grudev.github.io/SingleApplication/

Great! But we need to fix the link:

изображение

**Comment by Shatur** [comment]
Could you also put the link to documentation to the repo description?
изображение

изображение

**Comment by itay-grudev** [comment]
@Shatur Done.

**Pull request merged**
