### PR TITLE
fixed a typo

### PR DESCRIPTION
**Pull request by pbek**
Thank you for this great library, I use it in https://github.com/pbek/QOwnNotes!

### CODE REVIEW

**Comment by itay-grudev** [comment]
Just last night I built QOwnNotes from source on my computer and I noticed. :D
It's really nice feeling to know that you've worked on something useful.

Though I don't think you were using the latest version while it contains some important bug fixes.

**Comment by pbek** [comment]
> Just last night I built QOwnNotes from source on my computer and I noticed. :D

I didn't know that you are using it! Awesome! How did you find out about it?

> It's a really nice feeling - to know that you've worked on something useful.

Thanks a lot for it! :+1:

**Comment by itay-grudev** [comment]
> How did you find out about it?
I don't remember, really.  I am using Nextcloud, so maybe from there. I've used it for some time now, though. I just got a new Linux computer and build it for my new machine and peeked into the source.

**Comment by pbek** [comment]
> I just got a new Linux computer and build it for my new machine

because of lack of a repository for it? :laughing: what distribution are you using?

**Comment by itay-grudev** [comment]
This is a very strange coincidence.
I feel like you added a spyware in QOwnNotes and you know I know that you didn't PR your changes...

> because of lack of a repository for it? laughing what distribution are you using?

PureOS on a Librem 13.

**Comment by pbek** [comment]
> PureOS on a Librem 13.

being Debian-based you could possibly use the debian repository
nice, a Librem 13

> I feel like you added a spyware in QOwnNotes and you know I know that you didn't PR your changes...

what spyware and what changes?

**Pull request merged**
