### PR TITLE
feat: Add function numberOfInstances()

### LINKED ISSUE #89: Add a function which returns the number of running instances
This is helpful if you want to behave differently on different number of instances.

My actual need is described in coder3101/cp-editor#131, if you are interested in where this feature is useful.

### PR DESCRIPTION
**Pull request by ouuan**
This function returns the number of running instances, by adding a new variable in InstancesInfo.

This closes #89.

### CODE REVIEW

**Comment by ouuan** [comment]
I met a problem: The destructor is not called after `::exit()` is called, which is called in `QCommandLineParser` when the option contains `--help`, `--version` or invalid options, thus the count is not updated. I found that the destructors of variables declared with `static` will be called after `::exit()`, but that's not recommended for `QApplication`. Do you have any solutions?

**Comment by ouuan** [comment]
What's more, it would fail if one instance crashed. Maybe it's a good idea to use LocalServer to check?

**Comment by ouuan** [comment]
I have a solution which can deal with QCommandLineParser, but not crash:

Use `qAddPostRoutine` to add a function which reduces `numberOfInstances`.

**Comment by ouuan** [comment]
What about use LocalServer to send a message and wait for replies from other instances in 100ms?

**Comment by ouuan** [comment]
I came up with a trick: Call `detach()` and check if the shared memory is destroyed.

**Comment by ouuan** [comment]
I don't know which solution is the best, or if there are better solutions. However, this PR may be useless. Close this if you like, or tell me how to improve it so that it works correctly after a crash.

**Comment by itay-grudev** [comment]
Yhea. An instance crashing is a serious problem I had to deal with. here is not much you can do about it. Also the Qt `Q[Core]Application` constructors and places where they just call `::exit()` internally. You may be correct that number of instances maybe really hard to achieve with exception to pinging other instances to check for activity, which solution I don't really like because it consumes resources.

I'll think about it for a bit and if I can't come up with an alternative I will close it.

**Comment by ouuan** [comment]
Close this in favor of #91

**Pull request closed without merging**
