### PR TITLE
Adaptation to Qt's pimpl idiom design. Improved inheritance safety.

### PR DESCRIPTION
**Pull request by i7achi**
Details:
* Improved unsafe C-style macros inheritance approach to the project-wide
DEFINES: it is unspecified in
which order source files are being preprocessed ones, so in
singleapplication.cpp the class might be inherent of default-specified
base, while in main.cpp this can be a user-provided QAPPLICATION_CLASS
definition.

* Replace Qt's pseudo-keywords to more library-independent counterparts
('emit -> Q_EMIT', etc)

* Indentation fixes (80 character column-width)

* Rearragned #include statements: from most platform-independen to more
app-specific.

* Fixed some grammar typos.

* README.md updated respectively.

### CODE REVIEW

**Comment by itay-grudev** [comment]
Thanks. I am really busy this and next week. I'll review and and test it but that probably won't be before next Friday.

**Comment by i7achi** [comment]
@itay-grudev  Ok. Thank you for the great job. I hope my small changes will be useful :)

**Comment by itay-grudev** [comment]
Sorry for the late response. Thank you for the improvments. Since you are breaking my established API, I would like to ask you to add the following to your `singleapplication.h` before the include statement for the `QAPPLICATION_CLASS`:
```cpp
#ifndef QAPPLICATION_CLASS
  #define QAPPLICATION_CLASS QApplication
#endif
```
This will make sure that the QAPPLICATION_CLASS has a default value of `QApplication` and you wouldn't need to change your project file for most applications.

And two small cosmetic changes for consistency. First can you remove the `.` at the end of the comment on `singleapplication.cpp:118`. And second can you remove the extra indentation of the `QWindow`/`showUp()` code sample so the closing brackets match the indentation of the opening bracket and the code inside is indented only once.

Thanks.

**Comment by i7achi** [comment]
I lost sight of that... You're right, of course. Done!
Any suggestion?

**Pull request merged**
