### PR TITLE
Use qgetenv instead of QProcess/whoami to get username

### PR DESCRIPTION
**Pull request by jonaski**

### CODE REVIEW

**Comment by itay-grudev** [comment]
I think `whoami` is more reliable than `$USER` as the latter can be easily changed. Unless you can show me a use case where that may be useful...

**Comment by jonaski** [comment]
If you want I can make a PR to use geteuid/getpwuid directly for Linux, and just fallback to whoami on other unix systems where that's not supported.

**Comment by itay-grudev** [comment]
@jonaski Is this for performance reasons?

**Comment by jonaski** [comment]
For performance reasons, and it's more reliable than using whoami (and I dont like it). Also, technically the home folder path name can be different than the username. I've seen cases where it times out and fallback to the user directory.

**Comment by itay-grudev** [comment]
@jonaski Why did you close this PR?

**Pull request closed without merging**
