### PR TITLE
bugfix - change QApplication to macro QAPPLICATION_CLASS

### PR DESCRIPTION
**Pull request by BG4444**
Fix error with QCoreApplication project

### CODE REVIEW

**Comment by itay-grudev** [comment]
That does make sense. But wouldn't it be better if we just use [QCoreApplication](https://doc.qt.io/qt-5/qcoreapplication.html#instance)?

**Comment by BG4444** [comment]
Yes, it's better solution.

**Comment by itay-grudev** [comment]
If you make a PR with the change can you give me your name so I can give you credit in my CHANGELOG?

**Comment by BG4444** [comment]
Oh, thank you - my name is Evgeniy Bazhenov.

**Comment by itay-grudev** [comment]
Thanks a lot.
https://github.com/itay-grudev/SingleApplication/blob/master/CHANGELOG.md#308

**Pull request merged**
