### PR TITLE
Add an option to disable Doxygen

### PR DESCRIPTION
**Pull request by Shatur**
Was discussed in https://github.com/itay-grudev/SingleApplication/pull/157#issuecomment-1148744660

### CODE REVIEW

**Comment by itay-grudev** [comment]
Can we make it the other way around? So we don't break any builds? An option to enable doxygen?

**Comment by Shatur** [comment]
Do you mean turn it off by default?

**Comment by itay-grudev** [comment]
Yes, because as you mentioned it might break offline builds like yours.

**Comment by Shatur** [comment]
> Yes, because as you mentioned it might break offline builds like yours.

Yes, this is why I introducing the option - I will be able to disable it on my side. But we can disable it by default if you want.

Also are you agree with the name of the option?

**Comment by itay-grudev** [comment]
Yes, it's fine.

**Comment by Shatur** [comment]
Could you enable this option in the repo settings?

изображение

And could you also setup "branch protection" settings to require CI pass before merge? This will allow us "automerge" PRs on CI pass :)

**Comment by itay-grudev** [comment]
`master` should have been protected. Microsoft has ducked something up again.

**Pull request merged**
