### PR TITLE
Added missing "QMutex" dependencies

### PR DESCRIPTION
**Pull request by uralbash**

### CODE REVIEW

**Comment by itay-grudev** [comment]
Is that really necessary? `singleapplication_p.h` includes `singleapplication.h` which includes `QMutex`.

**Comment by uralbash** [comment]
But I can't see ``QMutex`` in ``singleapplication.h`` https://github.com/itay-grudev/SingleApplication/blob/master/singleapplication.h perhaps it should be moved from cpp file to h

**Comment by itay-grudev** [comment]
You are correct. It's only in the `singleapplication.cpp`. Can you also remove the include in `singleapplication.cpp` and I'll accept it.

**Comment by uralbash** [comment]
@itay-grudev fixed

**Comment by itay-grudev** [comment]
Sorry for the misunderstanding. QMutex is only an implementation detail and should be in `singleapplication_p.h`.

**Pull request merged**
