### PR TITLE
Refactor CI

### PR DESCRIPTION
**Pull request by Shatur**
In this PR, I added CI skip for Markdown files, added QMake, specified -j2 to speedup building and formatted the workflow file.

### CODE REVIEW

**Review by itay-grudev — DISMISSED** [review]

**Comment by Shatur** [comment]
@itay-grudev, may I ask you to add `hacktoberfest` label to the repo?

**Comment by itay-grudev** [comment]
@Shatur Go for it.

**Comment by Shatur** [comment]
> @Shatur Sure. How?

Just add `hactoberfest` topic as described here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by itay-grudev** [comment]
@Shatur Done. Also no-way that `-j2` works. I think these runners are single threaded.

**Comment by Shatur** [comment]
> @Shatur Done. Also no-way that -j2 works. I think these runners are single threaded.

Are you sure? [The specification](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) says that machines have at least two cores.

**Comment by itay-grudev** [comment]
> > @Shatur Done. Also no-way that -j2 works. I think these runners are single threaded.
> 
> Are you sure? [The specification](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources) says that machines have at least two cores.

Wow! It really did shave-off a few seconds. Nice.

**Comment by itay-grudev** [comment]
@Shatur From what I read about this there is some weirdness with `make` on `MSVC` where it doesn't fancy `\t` and prefers 4 spaces.

**Comment by Shatur** [comment]
> @Shatur From what I read about this there is some weirdness with make on MSVC where it doesn't fancy \t and prefers 4 spaces.

It looks like `make` on Windows machines executes `mingw-make`, but we want to run it with `nmake` (from MSVC).

**Comment by Shatur** [comment]
Done :)

**Review by itay-grudev — APPROVED** [review]

**Pull request merged**
