### PR TITLE
removed c style casts and eliminated all clang warnings, ... 

### PR DESCRIPTION
**Pull request by jbuckmccready**
fixed instanceId reading from only one byte in deserialization of message, cleaned up serialization code using QDataStream, changed connection type to use quint8 enum rather than char

I loosely/quickly tested these changes on windows 7 using mingw 5.3 and msvc 2017.

### CODE REVIEW

**Comment by jbuckmccready** [comment]
I think it's more clear with the enum cases explicitly initialized, but technically they had to have those values regardless. The compiler is not allowed to give them any values it wants, the C++ standard (and C standard) forces any uninitialized enum values to be equal to the previous declared value + 1 or 0 if there are no previous values (see discussion [here](https://stackoverflow.com/questions/6434105/are-default-enum-values-in-c-the-same-for-all-compilers#6434122) and link to standard section [here](http://eel.is/c++draft/dcl.enum)).

**Comment by itay-grudev** [comment]
@jbuckmccready Hmm. You are correct. The enum values are perfectly fine.

**Comment by itay-grudev** [comment]
Thanks. I'll test it when I have time and merge it afterwards. Can you give me your name so I can give you credit in my `CHANGELOG.md`?

**Comment by jbuckmccready** [comment]
Jedidiah Buck McCready

**Comment by itay-grudev** [comment]
Regarding the fact that this is a "breaking" change, it is a change in the internal communication method. Thus it should be perfectly fine.

**Comment by jbuckmccready** [comment]
Yep, I just mentioned it since an application built with the previous version will fail to communicate with an application built with this version (a strange use case, but not impossible scenario).

**Comment by itay-grudev** [comment]
Yhea, I know that. But it shouldn't happen in practice. At the very least I use the application version number to compute the shared memory block name. In a well written production app, the new version should create an entirely new SingleApplication scope. Also keep in mind that if it indeed happened that a new version communicates with an older version, the new connection will simply be detected as invalid and dropped.

**Pull request merged**
